# Generated by Django 2.2.3 on 2019-07-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbpost', '0004_auto_20190705_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='fbpost.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fbpost.Post'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
