# Generated by Django 2.2.2 on 2019-06-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
